make makef and nob the same

diff --git a/makef b/makef
--- a/makef
+++ b/makef
@@ -4,9 +4,19 @@ while [ $loop = true ] ; do
     if [ -f "Makefile" ] || [ -f "makefile" ] ; then
         exec make $@
     fi
+    if [ -f "nob" ] ; then
+        exec ./nob $@
+    fi
+    if [ -f "nob.c" ] ; then
+        echo "cc nob.c -o nob"
+        cc nob.c -o nob || die "failed to compile nob"
+        exec ./nob $@
+    fi
     if [ "$PWD" = "/" ] ; then
         loop=false
     else
         cd ..
     fi
 done
+echo "failed to find makefile/nob"
+exit 5
diff --git a/nob b/nob
--- a/nob
+++ b/nob
@@ -1,6 +1,9 @@
 #!/usr/bin/sh
 loop=true
 while [ $loop = true ] ; do
+    if [ -f "Makefile" ] || [ -f "makefile" ] ; then
+        exec make $@
+    fi
     if [ -f "nob" ] ; then
         exec ./nob $@
     fi
@@ -15,3 +18,5 @@ while [ $loop = true ] ; do
         cd ..
     fi
 done
+echo "failed to find makefile/nob"
+exit 5
